<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;

/**
 * @Implements hook_form_FORM_ID_alter()
 */
function nodeinfo_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_record_form') {
    // Hide the title field
    $form['title']['#access'] = FALSE;
    $form['#entity_builders'][] = '_nodeinfo_node_recorder_title_builder';
  }
}
/**
 * automated generate node title
 */
function _nodeinfo_node_recorder_title_builder($entity_type, NodeInterface $node, $form, FormStateInterface $form_state) {
  if ($node->bundle() == 'record') {
    $date_of_record = $node->field_record_date->date->format('Ymd');   // format('Y-m-d')
    $hospital_name = \Drupal::getContainer()->get('flexinfo.field.service')->getFieldFirstTargetIdTermName($node, 'field_record_hospital');

    $node->setTitle($hospital_name  . $date_of_record);
  }
}
